Repository ros2/rmw_opensplice, pull requests merged in 2018-11, with the labels that each got.

#245 use new error handling API from rcutils
  rmw_opensplice_cpp/src/rmw_node.cpp
  rmw_opensplice_cpp/src/rmw_node_names.cpp
  rmw_opensplice_cpp/src/rmw_service_names_and_types.cpp
  rmw_opensplice_cpp/src/rmw_topic_names_and_types.cpp
  rmw_opensplice_cpp/src/types.cpp
Labels: enhancement, in review

#250 suppress warning on Windows
  rmw_opensplice_cpp/src/qos.hpp
  rmw_opensplice_cpp/src/rmw_client.cpp
  rmw_opensplice_cpp/src/rmw_guard_condition.cpp
  rmw_opensplice_cpp/src/rmw_init.cpp
  rmw_opensplice_cpp/src/rmw_node.cpp
  rmw_opensplice_cpp/src/rmw_publisher.cpp
  rmw_opensplice_cpp/src/rmw_service.cpp
  rmw_opensplice_cpp/src/rmw_service_server_is_available.cpp
  rmw_opensplice_cpp/src/rmw_subscription.cpp
  rmw_opensplice_cpp/src/rmw_trigger_guard_condition.cpp
  rmw_opensplice_cpp/src/rmw_wait.cpp
  rmw_opensplice_cpp/src/rmw_wait_set.cpp
  rmw_opensplice_cpp/src/types.hpp
Labels: in review

#248 Methods to retrieve matched counts on pub/sub
  rmw_opensplice_cpp/src/rmw_publisher.cpp
  rmw_opensplice_cpp/src/rmw_subscription.cpp
  rmw_opensplice_cpp/src/types.cpp
  rmw_opensplice_cpp/src/types.hpp
Labels: in progress

#247 add opensplice support for cdr serialization
  rmw_opensplice_cpp/src/rmw_publish.cpp
  rmw_opensplice_cpp/src/rmw_serialize.cpp
  rmw_opensplice_cpp/src/rmw_subscription.cpp
  rmw_opensplice_cpp/src/rmw_take.cpp
Labels: in review

#246 refactor to support init options and context
  rmw_opensplice_cpp/src/rmw_guard_condition.cpp
  rmw_opensplice_cpp/src/rmw_init.cpp
  rmw_opensplice_cpp/src/rmw_node.cpp
Labels: enhancement, in review
