Repository ros2/rmw_opensplice, pull requests merged in 2018-06, with the labels that each got.

#225 Remove topic partitions
  rmw_opensplice_cpp/src/rmw_publisher.cpp
  rmw_opensplice_cpp/src/rmw_subscription.cpp
  rmw_opensplice_cpp/src/types.cpp
  rosidl_typesupport_opensplice_cpp/include/rosidl_typesupport_opensplice_cpp/misc.hpp
  rosidl_typesupport_opensplice_cpp/include/rosidl_typesupport_opensplice_cpp/requester.hpp
  rosidl_typesupport_opensplice_cpp/include/rosidl_typesupport_opensplice_cpp/responder.hpp
  rosidl_typesupport_opensplice_cpp/src/misc.cpp
Labels: in review

#228 gracefully fail when using serialized functions
  rmw_opensplice_cpp/CMakeLists.txt
  rmw_opensplice_cpp/src/rmw_publish.cpp
  rmw_opensplice_cpp/src/rmw_serialize.cpp
  rmw_opensplice_cpp/src/rmw_take.cpp
Labels: in progress

#230 export / use typesupport libraries separately
  rosidl_typesupport_opensplice_c/cmake/rosidl_typesupport_opensplice_c_generate_interfaces.cmake
  rosidl_typesupport_opensplice_cpp/cmake/rosidl_typesupport_opensplice_cpp_generate_interfaces.cmake
Labels: enhancement, in review

#231 OpenSplice env hook: Extra fix for paths with spaces in them
  opensplice_cmake_module/env_hook/opensplice.bat.in
Labels: in review

#233 Export OSPL_HOME in env hook
  opensplice_cmake_module/env_hook/opensplice.bat.in
  opensplice_cmake_module/env_hook/opensplice.sh.in
Labels: in review

#236 Split typesupport and cmake module packages into another repository.
  opensplice_cmake_module/CMakeLists.txt
  opensplice_cmake_module/cmake/Modules/FindOpenSplice.cmake
  opensplice_cmake_module/config/ros_ospl.xml
  opensplice_cmake_module/env_hook/opensplice.bat.in
  opensplice_cmake_module/env_hook/opensplice.sh.in
  opensplice_cmake_module/opensplice_cmake_module-extras.cmake
  opensplice_cmake_module/package.xml
  rosidl_typesupport_opensplice_c/CMakeLists.txt
  rosidl_typesupport_opensplice_c/bin/rosidl_typesupport_opensplice_c
  rosidl_typesupport_opensplice_c/cmake/rosidl_typesupport_opensplice_c_generate_interfaces.cmake
  rosidl_typesupport_opensplice_c/include/rosidl_typesupport_opensplice_c/identifier.h
  rosidl_typesupport_opensplice_c/include/rosidl_typesupport_opensplice_c/visibility_control.h
  rosidl_typesupport_opensplice_c/package.xml
  rosidl_typesupport_opensplice_c/resource/msg__rosidl_typesupport_opensplice_c.h.em
  rosidl_typesupport_opensplice_c/resource/msg__type_support_c.cpp.em
  rosidl_typesupport_opensplice_c/resource/rosidl_typesupport_opensplice_c__visibility_control.h.in
  rosidl_typesupport_opensplice_c/resource/srv__rosidl_typesupport_opensplice_c.h.em
  rosidl_typesupport_opensplice_c/resource/srv__type_support_c.cpp.em
  rosidl_typesupport_opensplice_c/rosidl_typesupport_opensplice_c-extras.cmake.in
  rosidl_typesupport_opensplice_c/rosidl_typesupport_opensplice_c/__init__.py
  rosidl_typesupport_opensplice_c/src/identifier.cpp
  rosidl_typesupport_opensplice_cpp/CMakeLists.txt
  rosidl_typesupport_opensplice_cpp/bin/rosidl_typesupport_opensplice_cpp
  rosidl_typesupport_opensplice_cpp/cmake/rosidl_typesupport_opensplice_cpp_generate_interfaces.cmake
  rosidl_typesupport_opensplice_cpp/include/rosidl_typesupport_opensplice_cpp/identifier.hpp
  rosidl_typesupport_opensplice_cpp/include/rosidl_typesupport_opensplice_cpp/impl/error_checking.hpp
  rosidl_typesupport_opensplice_cpp/include/rosidl_typesupport_opensplice_cpp/message_type_support.h
  rosidl_typesupport_opensplice_cpp/include/rosidl_typesupport_opensplice_cpp/message_type_support_decl.hpp
  rosidl_typesupport_opensplice_cpp/include/rosidl_typesupport_opensplice_cpp/misc.hpp
  rosidl_typesupport_opensplice_cpp/include/rosidl_typesupport_opensplice_cpp/requester.hpp
  rosidl_typesupport_opensplice_cpp/include/rosidl_typesupport_opensplice_cpp/responder.hpp
  rosidl_typesupport_opensplice_cpp/include/rosidl_typesupport_opensplice_cpp/service_type_support.h
  rosidl_typesupport_opensplice_cpp/include/rosidl_typesupport_opensplice_cpp/service_type_support_decl.hpp
  rosidl_typesupport_opensplice_cpp/include/rosidl_typesupport_opensplice_cpp/u__instanceHandle.h
  rosidl_typesupport_opensplice_cpp/include/rosidl_typesupport_opensplice_cpp/visibility_control.h
  rosidl_typesupport_opensplice_cpp/package.xml
  rosidl_typesupport_opensplice_cpp/resource/msg__rosidl_typesupport_opensplice_cpp.hpp.em
  rosidl_typesupport_opensplice_cpp/resource/msg__type_support.cpp.em
  rosidl_typesupport_opensplice_cpp/resource/srv__rosidl_typesupport_opensplice_cpp.hpp.em
  rosidl_typesupport_opensplice_cpp/resource/srv__type_support.cpp.em
  rosidl_typesupport_opensplice_cpp/resource/visibility_control.h.in
  rosidl_typesupport_opensplice_cpp/rosidl_typesupport_opensplice_cpp-extras.cmake.in
  rosidl_typesupport_opensplice_cpp/rosidl_typesupport_opensplice_cpp/__init__.py
  rosidl_typesupport_opensplice_cpp/rosidl_typesupport_opensplice_cpp/rosidl_generator_dds_idl_extension.py
  rosidl_typesupport_opensplice_cpp/src/identifier.cpp
  rosidl_typesupport_opensplice_cpp/src/misc.cpp
  rosidl_typesupport_opensplice_cpp/src/u_instanceHandle.c
Labels: in progress

#238 Prepare 0.5.0
  rmw_opensplice_cpp/package.xml
Labels: in review

#235 accept RETCODE_PRECONDITION_NOT_MET when detaching condition
  rmw_opensplice_cpp/src/rmw_wait.cpp
Labels: bug, in review

#240 Don't error if Sample_ prefix not found in service type
  rmw_opensplice_cpp/src/rmw_service_names_and_types.cpp
Labels: in review
